name: Build Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing prerequisites pip + build
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Building  package
        run: python -m build

      - name: Attach artefacts to the GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
